import type {Metadata} from "next";
import {Inter} from "next/font/google"; // Используем Inter вместо Geist
import "./globals.css";
import Link from "next/link";

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body className={`${inter.variable} antialiased`}>
        <header className="flex justify-around py-3">
            <Link href={'/'}>
                <h1 className="font-bold text-3xl">Новостной портал</h1>
            </Link>
            <div className="flex items-center">
                <Link className="mx-2" href="/about">
                    О нас
                </Link>
                <Link className="mx-2" href="/contacts">
                    Контакты
                </Link>
            </div>
        </header>
        <main>{children}</main>
        {/* Контент страниц будет здесь */}
        </body>
        </html>
    );
}